### ISSUE TITLE
What can it be used at?

### ISSUE THREAD

**Issue by piotr-yuxuan** [clj-commons/ordered#38]
Hi, thanks for that free project :-)

I'm actually using it because it's a dependence of https://github.com/owainlewis/yaml but I don't understand when to purposefully use sorted sets. Would you mind to tell me when I would benefit to use such a datastructure?

Thanks in advance.

**Comment by piotr-yuxuan** [comment]
Plus, what the difference between `ordered` and built-in [`sorted-map`](https://clojuredocs.org/clojure.core/sorted-map) and [`sorted-set`](https://clojuredocs.org/clojure.core/sorted-set) available from Clojure 1.0? Thanks in advance for your reply.

**Comment by jafingerhut** [comment]
I will give an answer that mostly only mentions sorted-set and ordered sets, but the same reasons apply to sorted-map and ordered maps.

So a sorted-set of integers with the default comparison function will always maintain the integers in order from minimum to maximum value, regardless of the order that you add the integers to the set.

An ordered set of integers will always maintain them in the order that they were added to the set, regardless of their value.

One reason that ordered sets can be useful is that they can help you create debug output and/or data files containing printed representations of those sets, with an order that is repeatable across runs.  If one run adds most of the same elements, but say one or a few more elements than an earlier run, and most of the elements are added in the same order, using a tool like 'diff' to compare the text files and find differences can make the output order similar enough that 'diff' gives short output, rather than a much longer output because of more differences in order.

I am sure there are other more significant reasons than this where remembering insertion order is important, but I'm not coming up with another at the moment.

**Comment by piotr-yuxuan** [comment]
Also, it can be useful with something like ordering clauses:

```
[[:a/b :asc]
 [:a/c :desc]]
```

when you want to keep the order but at some point in the code you're likely to retrieve (or change) the orientation of key.

**Comment by danielcompton** [comment]
Will close this question now, but thanks for chipping in @jafingerhut, I hadn't thought about the debugging use-case for insertion ordered collections. Thanks!
